### ISSUE TITLE
Idea: unify `inject` and `extract` into a single action

### ISSUE THREAD

**Issue by AkihiroSuda** [overmindtech/buildkit-cache-dance#7]
Would it be possible to unify `inject` and `extract` into a single action?

Probably like this: https://github.com/actions/cache/blob/v3.3.2/action.yml#L34-L35
```yaml
runs:
  main:  `./inject.sh`
  post: `./extract.sh`
```
